.TH USAGE: "1" "May 2013" "Usage: deathgrip [options]" "User Commands"
.SH NAME
deathgrip -  a program to cryptographically encode plain text documents.
.SH DESCRIPTION
Deathgrip is a Python-based program which is used to encrypt and decript plain text messages by converting letters to numbers and using a mathmatical algorithm based on the time, date, and random integers. 
.SH SYNOPSIS
.B deathgrip
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-i\fR FOO, \fB\-\-input\fR=\fIFOO\fR
write report to a file
.TP
\fB\-o\fR BAR, \fB\-\-output\fR=\fIBAR\fR
specify output to a file
.TP
\fB\-c\fR FOO, \fB\-\-config\fR=\fIFOO\fR
write report to a file
.TP
\fB\-v\fR, \fB\-\-verbose\fR
print output
.TP
\fB\-e\fR, \fB\-\-encode\fR
print output
.TP
\fB\-d\fR, \fB\-\-decode\fR
print output
.TP
\fB\-\-dry\-run\fR
same as verbose with no output file
.PP
deathgrip: error: no such option: \fB\-\-version\fR
.SH FILES
Unless a configuration file is specified, deathgrip firsts looks in the present working directory, then the users home folder, and finally at 
.I /etc/deathgrip.conf 
for a configuration file. It is recomended that you copy the default congif to 
.I ~/.config/deathgrip/deathgrip.conf
.SH "SEE ALSO"
The full documentation for Deathgrip is avaialble at http://github.com/super-nathan/deathgrip
.SH AUTHORS
Joseph Ko (eaglclaws@hotmail.com)
"Super" Nathan Weber (supernathansunshine@gmail.com)
