.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.41.2.
.TH USAGE: "1" "May 2013" "Usage: deathgrip [options]" "User Commands"
.SH NAME
Usage: \- manual page for Usage: deathgrip [options]
.SH SYNOPSIS
.B deathgrip
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-i\fR FOO, \fB\-\-input\fR=\fIFOO\fR
write report to a file
.TP
\fB\-o\fR BAR, \fB\-\-output\fR=\fIBAR\fR
specify output to a file
.TP
\fB\-c\fR FOO, \fB\-\-config\fR=\fIFOO\fR
write report to a file
.TP
\fB\-v\fR, \fB\-\-verbose\fR
print output
.TP
\fB\-e\fR, \fB\-\-encode\fR
print output
.TP
\fB\-d\fR, \fB\-\-decode\fR
print output
.TP
\fB\-\-dry\-run\fR
same as verbose with no output file
.PP
deathgrip: error: no such option: \fB\-\-version\fR
.SH "SEE ALSO"
The full documentation for
.B Usage:
is maintained as a Texinfo manual.  If the
.B info
and
.B Usage:
programs are properly installed at your site, the command
.IP
.B info Usage:
.PP
should give you access to the complete manual.
